import './style.css'
import { Inter } from 'next/font/google'
import { Header, Footer, CustomCursor } from './components'
import 'typeface-oswald';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet" />
      </head>

      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <CustomCursor />
      </body>
    </html>
  )
}

