import './style.css'
import { Inter } from 'next/font/google'
import { Header, Footer, CustomCursor } from './components'
import 'typeface-oswald';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Modern Interior Design',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <link rel="preload" href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" as="style" onload="this.onload=null; this.rel='stylesheet'" />
          <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" /></noscript>
      </head>

      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <CustomCursor />
      </body>
    </html>
  )
}

